### ISSUE TITLE
Slot file-preview-new and hover

### ISSUE THREAD

**Issue by lelikflegma** [safrazik/vue-file-agent#63] opened 2020-05-17 09:12 UTC
Hi.
I'm trying use slot file-preview-new and i need use "hover" event on icon to show tooltip :
```html
<VueFileAgent
...
>
	<template v-slot:file-preview-new>
		<div key="new">
			<img src="/img/icon.png" id="tooltip-test">
			<b-tooltip target="tooltip-test" triggers="hover">
				<p>{{ helpText }}</p>
			</b-tooltip>
		</div>
	</template>
</VueFileAgent>
```

Problem is that "hover" event do not triggers on mouse over icon...

**Comment by safrazik** [comment] 2020-05-17 14:50
It's an expected behavior. The hidden `<input type="file"` is stacked on top - for platform file selection dialog to open on click - with a `z-index` value of `10`

You can change the intended behavior with `z-index`  value of `10+` but you might end up unwanted side effects. (e.g: the help text will not be clickable)

```html
<b-tooltip style="position: relative; z-index: 20" target="tooltip-test" triggers="hover">
  <p>{{ helpText }}</p>
</b-tooltip>
```

---

Closing the issue as this is a hard to achieve thing without compromising intended behaviors. Please suggest if you have any alternative solutions.

**Closed by safrazik** 2020-05-17 14:50 UTC

**Comment by safrazik** [comment] 2020-05-17 14:53
Followup comment:

I might have been wrong with the element to set z-index value. This could be the right element:

```html
<img style="position: relative; z-index: 20" src="/img/icon.png" id="tooltip-test">
```
